Repository michelleog2351/TeamProject_Cinema-Booking-System, pull requests merged in 2025-03, with the labels that each got.

#75 Film size2
  .DS_Store
  public/style.css
Labels: enhancement, Version2

#76 Dynamic seats remaining
  index.js
  model/theatre.js
  public/screening/createScreening.js
  public/screening/updateScreening.js
Labels: enhancement

#91 Home features
  CinemaDB.sql
  index.js
  model/film.js
  model/theatre.js
  public/Customer/Film/cFilm.html
  public/Customer/Film/cFilm.js
  public/Customer/Film/filmDetails.html
  public/Customer/Film/filmDetails.js
  public/Theatre/Theatre.html
  public/Theatre/Theatre.js
  public/Theatre/createTheatre.html
  public/Theatre/updateTheatre.html
  public/app.js
  public/booking/booking.html
  public/booking/booking.js
  public/booking/createBooking.html
  public/booking/createBooking.js
  public/booking/updateBooking.html
  public/film/createFilm.html
  public/film/film.html
  public/film/film.js
  public/film/updateFilm.html
  public/footer.js
  public/images/search.svg
  public/images/sort-alpha-down.svg
  public/images/sort-alpha-up-alt.svg
  public/index.html
  public/login.html
  public/login.js
  public/nav.js
  public/screening/createScreening.html
  public/screening/createScreening.js
  public/screening/screening.html
  public/screening/screening.js
  public/screening/updateScreening.html
  public/screening/updateScreening.js
  public/style.css
  public/theme.css
  public/user/createUser.html
  public/user/createUser.js
  public/user/updateUser.html
  public/user/user.html
Labels: Version3
